# git-cliff configuration for Conventional Commits
# Docs: https://git-cliff.org/docs

[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = "{{#each groups}}{{#if title}}\n## {{title}}\n{{/if}}\n{{#each commits}}- {{#if scope}}**{{scope}}:** {{/if}}{{message}}{{/each}}\n{{/each}}"
footer = "\n"
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "/^feat(?:\(.+\))?:/", group = "Features" },
  { message = "/^fix(?:\(.+\))?:/", group = "Fixes" },
  { message = "/^perf(?:\(.+\))?:/", group = "Performance" },
  { message = "/^refactor(?:\(.+\))?:/", group = "Refactoring" },
  { message = "/^docs(?:\(.+\))?:/", group = "Documentation" },
  { message = "/^test(?:\(.+\))?:/", group = "Tests" },
  { message = "/^build(?:\(.+\))?:/", group = "Build System" },
  { message = "/^ci(?:\(.+\))?:/", group = "Continuous Integration" },
  { message = "/^chore(?:\(.+\))?:/", group = "Chores", skip = true },
  { message = "/^style(?:\(.+\))?:/", group = "Style", skip = true },
]

[remote]
# used by orhun/git-cliff-action, safe to keep default
url = "https://github.com/${{ github.repository }}"
