services:
  go-thermal-printer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./config.docker.toml:/app/config.toml
